### ISSUE TITLE
"gradlew clean" is not cleaning old class files

### ISSUE THREAD

**Issue by surajadh** [Roteyping/Main-Repository#22]
I had to delete folder under tomcat manually, should that be deleted automatically while running gradlew clean or something like that. I had created AboutUsController before and deleted it but it keep checking for that file. Following was the error

java.io.FileNotFoundException: class path resource [myhh/site/controllers/AboutUsController.class] cannot be opened because it does not exist

To get around this I deleted _ folder under tomcat and it worked

**Comment by nabinnepal** [comment]
This should be fixed now.
